version: "3"
services:
  webserve:
    image: nginx
    ports:
      - 83:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/:/var/www/html:ro
    depends_on:
      - php
  php:
    image: php:8.2.4-fpm
    volumes:
      - ./web/:/var/www/html
